import bscIcon from '../assets/bsc.png'
import ethIcon from '../assets/eth.png'
import polygonIcon from '../assets/polygon.svg'
import { ethers } from 'ethers'

export const baseConfig = {
  defaultPrice: '1',
}

export const evmChains: Array<SimpleChain> = [
  // {
  //   chainName: 'testnetTheta',
  //   chainId: 365, //testnet
  //   rpcURL: 'https://eth-rpc-api-testnet.thetatoken.org/rpc',
  //   baseToken: {
  //     name: 'Tetha Fuel',
  //     symbol: 'TFUEL',
  //     chainId: 365,
  //     decimals: 18,
  //     chainName: 'Tetha',
  //     ethContract: ethers.constants.AddressZero,
  //     logoURI: 'https://assets.coingecko.com/coins/images/8029/small/1_0YusgngOrriVg4ZYx4wOFQ.png?1553483622',
  //   },
  // },
  // {
  //     tokenBridgeAddress: '0x3ee18B2214AFF97000D974cf647E7C347E8fa585',
  //     wChainId: 2,
  //     chainId: 1,
  //     chainName: 'Ethereum',
  //     fullChainName: 'Ethereum Mainnet',
  //     rpcURL: 'https://mainnet.infura.io/v3',
  //     currencySymbol: 'ETH',
  //     blockExplorer: 'https://etherscan.io',
  //     externalRpcURL: 'https://eth-mainnet.alchemyapi.io/v2/7GC0FyW8SoE7BOQGhPcNquNjKdOhAkgm',
  //     logoURI: ethIcon,
  //     baseToken: {
  //         solanaContract: '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs',
  //         name: 'ETH',
  //         symbol: 'ETH',
  //         wChainId: 2,
  //         chainId: 1,
  //         decimals: 18,
  //         chainName: 'Ethereum mainnet',
  //         isSolanaNative: false,
  //         ethContract: ethers.constants.AddressZero,
  //         coingeckoId: 'weth',
  //         wrappedAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
  //         logoURI: ethIcon,
  //     },
  // },
  // {
  //     tokenBridgeAddress: '0xB6F6D86a8f9879A9c87f643768d9efc38c1Da6E7',
  //     wChainId: 4,
  //     chainId: 56,
  //     fullChainName: 'Binance Smart Chain Mainnet',
  //     chainName: 'BSC',
  //     blockExplorer: 'https://bscscan.com',
  //     currencySymbol: 'BNB',
  //     rpcURL: 'https://bsc-dataseed1.binance.org',
  //     logoURI: bscIcon,
  //     baseToken: {
  //         solanaContract: '9gP2kCy3wA1ctvYWQk75guqXuHfrEomqydHLtcTCqiLa',
  //         name: 'Wrapped BNB',
  //         symbol: 'WBNB',
  //         wChainId: 4,
  //         chainId: 56,
  //         decimals: 18,
  //         chainName: 'Binance Smart Chain',
  //         isSolanaNative: false,
  //         ethContract: ethers.constants.AddressZero,
  //         coingeckoId: 'wbnb',
  //         wrappedAddress: '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
  //         logoURI: bscIcon,
  //     },
  // },
  // {
  //     tokenBridgeAddress: '0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE',
  //     wChainId: 5,
  //     chainId: 137,
  //     chainName: 'Polygon',
  //     fullChainName: 'Polygon',
  //     rpcURL: 'https://polygon-rpc.com',
  //     currencySymbol: 'MATIC',
  //     blockExplorer: 'https://polygonscan.com',
  //     externalRpcURL: 'https://polygon-mainnet.g.alchemy.com/v2/rX2NW-TfXUgdctNEj2kRSv9lY2521Ks6',
  //     logoURI: polygonIcon,
  //     baseToken: {
  //         solanaContract: 'Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG',
  //         name: 'Matic',
  //         symbol: 'MATIC',
  //         wChainId: 5,
  //         chainId: 137,
  //         decimals: 18,
  //         chainName: 'Polygon',
  //         isSolanaNative: false,
  //         coingeckoId: 'wmatic',
  //         ethContract: ethers.constants.AddressZero,
  //         wrappedAddress: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
  //         logoURI: polygonIcon,
  //     },
  // },
  // {
  //   tokenBridgeAddress: '0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE',
  //   wChainId: 5,
  //   chainId: 80001,
  //   chainName: 'Polygon Mumbai',
  //   fullChainName: 'Polygon Mumbai Testnet',
  //   rpcURL: 'https://rpc-mumbai.maticvigil.com/',
  //   currencySymbol: 'MATIC',
  //   blockExplorer: 'https://polygonscan.com',
  //   externalRpcURL: 'https://polygon-mainnet.g.alchemy.com/v2/rX2NW-TfXUgdctNEj2kRSv9lY2521Ks6',
  //   logoURI: polygonIcon,
  //   baseToken: {
  //     solanaContract: 'Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG',
  //     name: 'Matic',
  //     symbol: 'MATIC',
  //     chainId: 80001,
  //     decimals: 18,
  //     chainName: 'Polygon',
  //     isSolanaNative: false,
  //     ethContract: ethers.constants.AddressZero,
  //     wrappedAddress: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
  //     logoURI: polygonIcon,
  //   },
  // },
  // {
  //   // tokenBridgeAddress: '0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE',
  //   // wChainId: 5,
  //   chainId: 80001,
  //   chainName: 'Polygon Mumbai',
  //   // fullChainName: 'Polygon Mumbai Testnet',
  //   rpcURL: 'https://rpc-mumbai.maticvigil.com/',
  //   // currencySymbol: 'MATIC',
  //   // blockExplorer: 'https://polygonscan.com',
  //   // externalRpcURL: 'https://polygon-mainnet.g.alchemy.com/v2/rX2NW-TfXUgdctNEj2kRSv9lY2521Ks6',
  //   // logoURI: polygonIcon,
  //   baseToken: {
  //     solanaContract: 'Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG',
  //     name: 'Matic',
  //     symbol: 'MATIC',
  //     chainId: 80001,
  //     decimals: 18,
  //     chainName: 'Polygon',
  //     isSolanaNative: false,
  //     ethContract: ethers.constants.AddressZero,
  //     wrappedAddress: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
  //     logoURI: polygonIcon,
  //   },
  // },
  {
    // tokenBridgeAddress: '0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE',
    // wChainId: 5,
    chainId: 31337,
    chainName: 'Localhost',
    // fullChainName: 'Polygon Mumbai Testnet',
    rpcURL: 'http://localhost:8545',
    // currencySymbol: 'MATIC',
    // blockExplorer: 'https://polygonscan.com',
    // externalRpcURL: 'https://polygon-mainnet.g.alchemy.com/v2/rX2NW-TfXUgdctNEj2kRSv9lY2521Ks6',
    // logoURI: polygonIcon,
    baseToken: {
      // solanaContract: 'Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG',
      name: 'Matic',
      symbol: 'MATIC',
      chainId: 31337,
      decimals: 18,
      chainName: 'Polygon',
      isSolanaNative: false,
      ethContract: ethers.constants.AddressZero,
      wrappedAddress: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
      logoURI: polygonIcon,
    },
  },
  // {
  //     tokenBridgeAddress: '0x0e082F06FF657D94310cB8cE8B0D9a04541d8052',
  //     wChainId: 6,
  //     chainId: 43114,
  //     chainName: 'Avalanche (C-Chain)',
  // },
  // {
  //     tokenBridgeAddress: '0x7C9Fc5741288cDFdD83CeB07f3ea7e22618D79D2',
  //     wChainId: 10,
  //     chainId: 250,
  //     chainName: 'Fantom',
  // },
]
