const legitTokens: { [index: string]: Token[] } = {
  '1': [
    {
      solanaContract: 'So11111111111111111111111111111111111111112',
      name: 'Wrapped SOL',
      symbol: 'SOL',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xD31a59c85aE9D8edEFeC411D448f90841571b89c',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png',
    },
    {
      solanaContract: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      name: 'USD Coin',
      symbol: 'USDC',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x41f7B8b9b897276b7AAE926a9016935280b44E97',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png',
    },
    {
      solanaContract: 'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
      name: 'Serum',
      symbol: 'SRM',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xE3ADAA4fb7c92AB833Ee08B3561D9c434aA2A3eE',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/logo.png',
    },
    {
      solanaContract: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      name: 'USDT',
      symbol: 'USDT',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x1CDD2EaB61112697626F7b4bB0e23Da4FeBF7B7C',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB/logo.svg',
    },
    {
      solanaContract: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
      name: 'Wrapped Bitcoin (Sollet)',
      symbol: 'BTC',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x1f4e35D4380D91AF30eDca625C8d158019786299',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E/logo.png',
    },
    {
      solanaContract: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
      name: 'Marinade staked SOL (mSOL)',
      symbol: 'mSOL',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x756bFb452cFE36A5Bc82e4F5f4261A89a18c242b',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So/logo.png',
    },
    {
      solanaContract: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
      name: 'Raydium',
      symbol: 'RAY',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xE617dd80c621a5072bD8cBa65E9d76c07327004d',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/logo.png',
    },
    {
      solanaContract: 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
      name: 'Star Atlas',
      symbol: 'ATLAS',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xb9F747162AB1E95d07361f9048BcDF6eDdA9eEA7',
      decimals: 8,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx/logo.png',
    },
    {
      solanaContract: 'E5ndSkaB17Dm7CsD22dvcjfrYSDLCxFcMd6z8ddCk5wp',
      name: 'Aldrin',
      symbol: 'RIN',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xf51421C93BD9943f057CF5668a5FD6C7Ac3F66ae',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/E5ndSkaB17Dm7CsD22dvcjfrYSDLCxFcMd6z8ddCk5wp/logo.png',
    },
    {
      solanaContract: 'AR1Mtgh7zAtxuxGd2XPovXPVjcSdY3i4rQYisNadjfKy',
      name: 'Wrapped SUSHI (Sollet)',
      symbol: 'soSUSHI',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x443B18444F43797DEd227279a51D2E5F688cb625',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AR1Mtgh7zAtxuxGd2XPovXPVjcSdY3i4rQYisNadjfKy/logo.png',
    },
    {
      solanaContract: 'AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
      name: 'Aurory',
      symbol: 'AURY',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xFe81232e1C2475782085b094D6Aa212ddFEb6560',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP/logo.png',
    },
    {
      solanaContract: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
      name: 'Bonfida',
      symbol: 'FIDA',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x7306B6F1059611Db89d582950E64291465F351Fc',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp/logo.svg',
    },
    {
      solanaContract: '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
      name: 'Lido Staked SOL',
      symbol: 'stSOL',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x5A114487131513637aCcF739CC7aD78EA9FAbc34',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj/logo.png',
    },
    {
      solanaContract: 'xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW',
      name: 'Solanium',
      symbol: 'SLIM',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x1E6fC70D0f4807C933443426722d22149355d8cC',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW/logo.png',
    },
    {
      solanaContract: 'PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44',
      name: 'PRT (Parrot Protocol)',
      symbol: 'PRT',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xB601bD14386C1bb5b3d0C6132DCc8Ca241DbB89a',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44/logo.svg',
    },
    {
      solanaContract: 'kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6',
      name: 'KIN',
      symbol: 'KIN',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x5B2BC12576C25cF8178498a7E74597E74d6EcC92',
      decimals: 5,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/logo.png',
    },
    {
      solanaContract: 'CwChm6p9Q3yFrjzVeiLTTbsoJkooscof5SJYZc2CrNqG',
      name: 'ETHBULL',
      symbol: 'ETHBULL',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0xbA8d245a041F87AA5D790D12AC37c8AF21d7ec80',
      decimals: 6,
      logoURI: '',
    },
    {
      solanaContract: 'CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5',
      name: 'renBTC',
      symbol: 'renBTC',
      wChainId: 2,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: true,
      ethContract: '0x99fcA5214549Fc0fD5afDFab4a3fbC19FFE55c77',
      decimals: 8,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5/logo.png',
    },
    {
      solanaContract: '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs',
      name: 'Wrapped ETH',
      symbol: 'WETH',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
      logoURI: 'https://assets.coingecko.com/coins/images/2518/small/weth.png?1628852295',
    },
    {
      solanaContract: 'ChVzxWRmrTeSgwd3Ui3UumcN8KX7VK3WaD4KGeSKpypj',
      name: 'Sushi',
      symbol: 'SUSHI',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x6b3595068778dd592e39a122f4f5a5cf09c90fe2',
      logoURI: 'https://assets.coingecko.com/coins/images/12271/small/512x512_Logo_no_chop.png?1606986688',
    },
    {
      solanaContract: 'EzfgjvkSwthhgHaceR3LnKXUoRkP6NUhfghdaHAj1tUv',
      name: 'FTX Token',
      symbol: 'FTT',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x50d1c9771902476076ecfc8b2a83ad6b9355a4c9',
      logoURI: 'https://assets.coingecko.com/coins/images/9026/small/F.png?1609051564',
    },
    {
      solanaContract: '2wpTofQ8SkACrkZWrZDjXPitYa8AwWgX8AfxdeBRRVLX',
      name: 'Chainlink',
      symbol: 'LINK',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x514910771af9ca656af840dff83e8264ecf986ca',
      logoURI: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png?1547034700',
    },
    {
      solanaContract: '8FU95xFJhUUkyyCLU13HSzDLs7oC4QZdXQHL6SCeab36',
      name: 'Uniswap',
      symbol: 'UNI',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
      logoURI: 'https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png?1600306604',
    },
    {
      solanaContract: 'BXZX2JRJFjvKazM1ibeDFxgAngKExb74MRXzXKvgikxX',
      name: 'yearn.finance',
      symbol: 'YFI',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e',
      logoURI: 'https://assets.coingecko.com/coins/images/11849/small/yfi-192x192.png?1598325330',
    },
    {
      solanaContract: '9LzCMqDgTKYz9Drzqnpgee3SGa89up3a247ypMj2xrqM',
      name: 'Audius',
      symbol: 'AUDIO',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x18aaa7115705e8be94bffebde57af9bfc265b998',
      logoURI: 'https://assets.coingecko.com/coins/images/12913/small/AudiusCoinLogo_2x.png?1603425727',
    },
    {
      solanaContract: '3vAs4D1WE6Na4tCgt4BApgFfENbm8WY7q4cSPD1yM4Cg',
      name: 'Aave',
      symbol: 'AAVE',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
      logoURI: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png?1601374110',
    },
    {
      solanaContract: 'CbNYA9n3927uXUukee2Hf4tm3xxkffJPPZvGazc2EAH1',
      name: 'agEUR',
      symbol: 'AGEUR',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x1a7e4e63778b4f12a199c062f3efdd288afcbce8',
      logoURI: 'https://assets.coingecko.com/coins/images/19479/small/agEUR.png?1635283566',
    },
    {
      solanaContract: '7dgHoN8wBZCc5wbnQ2C47TDnBMAxG4Q5L3KjP67z8kNi',
      name: 'Decentraland',
      symbol: 'MANA',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x0f5d2fb29fb7d3cfee444a200298f468908cc942',
      logoURI: 'https://assets.coingecko.com/coins/images/878/small/decentraland-mana.png?1550108745',
    },
    {
      solanaContract: 'C6oFsE8nXRDThzrMEQ5SxaNFGKoyyfWDDVPw37JKvPTe',
      name: 'PAX Gold',
      symbol: 'PAXG',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x45804880de22913dafe09f4980848ece6ecbaf78',
      logoURI: 'https://assets.coingecko.com/coins/images/9519/small/paxg.PNG?1568542565',
    },
    {
      solanaContract: 'CiKu4eHsVrc1eueVQeHn7qhXTcVu95gSQmBpX4utjL9z',
      name: 'Shiba Inu',
      symbol: 'SHIB',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce',
      logoURI: 'https://assets.coingecko.com/coins/images/11939/small/shiba.png?1622619446',
    },
    {
      solanaContract: 'HysWcbHiYY9888pHbaqhwLYZQeZrcQMXKQWRqS7zcPK5',
      name: 'Axie Infinity',
      symbol: 'AXS',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0xbb0e17ef65f82ab018d8edd776e8dd940327b28b',
      logoURI: 'https://assets.coingecko.com/coins/images/13029/small/axie_infinity_logo.png?1604471082',
    },
    {
      solanaContract: 'HGsLG4PnZ28L8A4R5nPqKgZd86zUUdmfnkTRnuFJ5dAX',
      name: 'The Graph',
      symbol: 'GRT',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0xc944e90c64b2c07662a292be6244bdf05cda44a7',
      logoURI: 'https://assets.coingecko.com/coins/images/13397/small/Graph_Token.png?1608145566',
    },
    {
      solanaContract: '12uHjozDVgyGWeLqQ8DMCRbig8amW5VmvZu3FdMMdcaG',
      name: 'Akropolis',
      symbol: 'AKRO',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7',
      logoURI: 'https://assets.coingecko.com/coins/images/3328/small/Akropolis.png?1547037929',
    },
    {
      solanaContract: '4Hx6Bj56eGyw8EJrrheM6LBQAvVYRikYCWsALeTrwyRU',
      name: 'dYdX',
      symbol: 'DYDX',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x92d6c1e31e14520e676a687f0a93788b716beff5',
      logoURI: 'https://assets.coingecko.com/coins/images/17500/small/hjnIm9bV.jpg?1628009360',
    },
    {
      solanaContract: 'CobcsUrt3p91FwvULYKorQejgsm5HoQdv5T8RUZ6PnLA',
      name: 'ConstitutionDAO',
      symbol: 'PEOPLE',
      wChainId: 2,
      chainId: 1,
      decimals: 18,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x7a58c0be72be218b41c608b7fe7c5bb630736c71',
      logoURI: 'https://assets.coingecko.com/coins/images/20612/small/GN_UVm3d_400x400.jpg?1637294355',
    },
    {
      solanaContract: 'AjkPkq3nsyDe1yKcbyZT7N4aK4Evv9om9tzhQD3wsRC',
      name: '1inch',
      symbol: '1INCH',
      wChainId: 2,
      decimals: 18,
      chainId: 1,
      chainName: 'Ethereum mainnet',
      isSolanaNative: false,
      ethContract: '0x111111111117dc0aa78b770fa6a738034120c302',
      logoURI: 'https://assets.coingecko.com/coins/images/13469/small/1inch-token.png?1608803028',
    },
  ],
  '56': [
    {
      solanaContract: 'So11111111111111111111111111111111111111112',
      name: 'Wrapped SOL',
      symbol: 'SOL',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xfA54fF1a158B5189Ebba6ae130CEd6bbd3aEA76e',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png',
    },
    {
      solanaContract: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      name: 'USD Coin',
      symbol: 'USDC',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x91Ca579B0D47E5cfD5D0862c21D5659d39C8eCf0',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png',
    },
    {
      solanaContract: 'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
      name: 'Serum',
      symbol: 'SRM',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x12BeffdCEcb547640DC30e1495E4B9cdc21922b4',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/logo.png',
    },
    {
      solanaContract: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      name: 'USDT',
      symbol: 'USDT',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x49d5cC521F75e13fa8eb4E89E9D381352C897c96',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB/logo.svg',
    },
    {
      solanaContract: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
      name: 'Wrapped Bitcoin (Sollet)',
      symbol: 'BTC',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xA9dBcE5FE45f51Fb1FeFe8693b2bBAA9e5F8D0bB',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E/logo.png',
    },
    {
      solanaContract: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
      name: 'Marinade staked SOL (mSOL)',
      symbol: 'mSOL',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xF2beBF36994381595331Af1f11Eb4F8114eD2c09',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So/logo.png',
    },
    {
      solanaContract: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
      name: 'Raydium',
      symbol: 'RAY',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x13b6A55662f6591f8B8408Af1C73B017E32eEdB8',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/logo.png',
    },
    {
      solanaContract: 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
      name: 'Star Atlas',
      symbol: 'ATLAS',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x83850D97018f665EB746FBb8f18351e977d1b0D6',
      decimals: 8,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx/logo.png',
    },
    {
      solanaContract: '3JSf5tPeuscJGtaCp5giEiDhv51gQ4v3zWg8DGgyLfAB',
      name: 'Wrapped YFI (Sollet)',
      symbol: 'soYFI',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x359446eC76b147A055ad7dF90F38709D1907370F',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/3JSf5tPeuscJGtaCp5giEiDhv51gQ4v3zWg8DGgyLfAB/logo.png',
    },
    {
      solanaContract: 'AR1Mtgh7zAtxuxGd2XPovXPVjcSdY3i4rQYisNadjfKy',
      name: 'Wrapped SUSHI (Sollet)',
      symbol: 'soSUSHI',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x4cA3B71C150c1F318da9c05cb409dB236cD9FD30',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AR1Mtgh7zAtxuxGd2XPovXPVjcSdY3i4rQYisNadjfKy/logo.png',
    },
    {
      solanaContract: '9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE',
      name: 'WOOF',
      symbol: 'WOOF',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x5a16A1814Ef033679c7d0a8AF32fE910E3C25560',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE/logo.png',
    },
    {
      solanaContract: 'SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag',
      name: 'Sunny Governance Token',
      symbol: 'SUNNY',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x8e18E1F0fa101d683D1aBde0b061F66aa6380dCA',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag/logo.svg',
    },
    {
      solanaContract: 'GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz',
      name: 'Genopets',
      symbol: 'GENE',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xa9ECbf7D4d2d90c3A341E162540f8588f7FbA8BC',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz/logo.png',
    },
    {
      solanaContract: 'MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac',
      name: 'Mango',
      symbol: 'MNGO',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xDfe6Aee548B5Dc9CDf96fdADF5ED3bc770c01992',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac/token.png',
    },
    {
      solanaContract: 'MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K',
      name: 'Mercurial',
      symbol: 'MER',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x18D0FE336a2064c5f277741d29954D83fC0376E8',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K/logo.png',
    },
    {
      solanaContract: 'DFL1zNkaGPWm1BqAVqRjCZvHmwTFrEaJtbzJWgseoNJh',
      name: 'DeFi Land',
      symbol: 'DFL',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x142bF7462bdd7cEd89D9144575409a7ABd99c0D2',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/DFL1zNkaGPWm1BqAVqRjCZvHmwTFrEaJtbzJWgseoNJh/logo.png',
    },
    {
      solanaContract: 'dK83wTVypEpa1pqiBbHY3MNuUnT3ADUZM4wk9VZXZEc',
      name: 'Wrapped Aave (Sollet)',
      symbol: 'soAAVE',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xc262844d27224723766118E12bC7B9BcdE7BC51f',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/dK83wTVypEpa1pqiBbHY3MNuUnT3ADUZM4wk9VZXZEc/logo.png',
    },
    {
      solanaContract: 'StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT',
      name: 'Step',
      symbol: 'STEP',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xBad2D28192bf0068Ff00284137f081318dE787a1',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT/logo.png',
    },
    {
      solanaContract: 'GsNzxJfFn6zQdJGeYsupJWzUAm57Ba7335mfhWvFiE9Z',
      name: 'Dexlab',
      symbol: 'DXL',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x3DC82573e64454851C95432A6A763Ef297209980',
      decimals: 6,
      logoURI: 'https://raw.githubusercontent.com/dexlab-project/assets/master/dexlab/dexlab_symbol_logo.svg',
    },
    {
      solanaContract: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
      name: 'Samoyed Coin',
      symbol: 'SAMO',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x5283b237eDce5bFcBEB01C97298D71f5a994Ec68',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU/logo.png',
    },
    {
      solanaContract: '8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh',
      name: 'COPE',
      symbol: 'COPE',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x80Ca0D6D9f4560a396de02fb170B0BC9348A2D97',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh/logo.png',
    },
    {
      solanaContract: 'AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
      name: 'Aurory',
      symbol: 'AURY',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xF5a367b7809e5683538C93Ce638B9258A0B88271',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP/logo.png',
    },
    {
      solanaContract: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
      name: 'Saber Protocol Token',
      symbol: 'SBR',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x75344E5693ed5ecAdF4f292fFeb866c2cF8afCF1',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1/logo.svg',
    },
    {
      solanaContract: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
      name: 'Bonfida',
      symbol: 'FIDA',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xED6e7c148Dddf8deeAEc7c6c9E3F4069AA2Fe33d',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp/logo.svg',
    },
    {
      solanaContract: '3bRTivrVsitbmCTGtqwp7hxXPsybkjn4XLNtPsHqa3zR',
      name: 'Only1 (LIKE)',
      symbol: 'LIKE',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x122207a7061E19c0dD89305A7798224c97F075b8',
      decimals: 9,
      logoURI: 'https://only1.io/like-token.svg',
    },
    {
      solanaContract: '4dmKkXNHdgYsXqBHCuMikNQWwVomZURhYvkkX5c4pQ7y',
      name: 'Synthetify',
      symbol: 'SNY',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xacaCa3260a41715215A38BfB82d2221FC20c93CC',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4dmKkXNHdgYsXqBHCuMikNQWwVomZURhYvkkX5c4pQ7y/logo.png',
    },
    {
      solanaContract: '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
      name: 'Lido Staked SOL',
      symbol: 'stSOL',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x39C131bfCace0C5D2a6DA6fdf0Ba8c20C3A16f3C',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj/logo.png',
    },
    {
      solanaContract: 'TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs',
      name: 'Tulip',
      symbol: 'TULIP',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x5FFF208371047b8F50B97688981a1F1a046C9568',
      decimals: 6,
      logoURI: 'https://raw.githubusercontent.com/sol-farm/token-logos/main/tulip.png',
    },
    {
      solanaContract: 'xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW',
      name: 'Solanium',
      symbol: 'SLIM',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xE3CBa77f89349DB13c1a441B447E4E5dFa374662',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW/logo.png',
    },
    {
      solanaContract: 'AMdnw9H5DFtQwZowVFr4kUgSXJzLokKSinvgGiUoLSps',
      name: 'MOONLANA',
      symbol: 'MOLA',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x61ECC86E5D5990BC1EdDcA712689Cb24259626b9',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AMdnw9H5DFtQwZowVFr4kUgSXJzLokKSinvgGiUoLSps/logo.png',
    },
    {
      solanaContract: 'PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44',
      name: 'PRT (Parrot Protocol)',
      symbol: 'PRT',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xBbc0Ef4FC2B05Efcca23e36fA60A48DBC6E19424',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44/logo.svg',
    },
    {
      solanaContract: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
      name: 'Orca',
      symbol: 'ORCA',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x180646A8E543430f42300d8F12b63Dc5C871e119',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE/logo.png',
    },
    {
      solanaContract: 'kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6',
      name: 'KIN',
      symbol: 'KIN',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x03043561F1708471f07FC106cED204a2E8b20724',
      decimals: 5,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/logo.png',
    },
    {
      solanaContract: 'SLRSSpSLUTP7okbCUBYStWCo1vUgyt775faPqz8HUMr',
      name: 'Solrise Finance',
      symbol: 'SLRS',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x4eEe11381556EbDb078B6170E55f3E1805e1112b',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SLRSSpSLUTP7okbCUBYStWCo1vUgyt775faPqz8HUMr/logo.png',
    },
    {
      solanaContract: 'cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2',
      name: 'SolChicks',
      symbol: 'CHICKS',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x2C79098BcD3EF23A11125eb51BD312edFD5B402A',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2/logo.png',
    },
    {
      solanaContract: 'NFTUkR4u7wKxy9QLaX2TGvd9oZSWoMo4jqSJqdMb7Nk',
      name: 'Blockasset',
      symbol: 'BLOCK',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xbC7A566b85eF73F935e640A06b5a8b031Cd975Df',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/NFTUkR4u7wKxy9QLaX2TGvd9oZSWoMo4jqSJqdMb7Nk/logo.png',
    },
    {
      solanaContract: 'FnKE9n6aGjQoNWRBZXy4RW6LZVao7qwBonUbiD7edUmZ',
      name: 'Sypool',
      symbol: 'SYP',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xBA1Ee032E9eD59AD0c0216e55C561767529615FB',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/b0e47e39f84cffb655f406eb569c57a88b5211cc/assets/mainnet/FnKE9n6aGjQoNWRBZXy4RW6LZVao7qwBonUbiD7edUmZ/logo.png',
    },
    {
      solanaContract: '6kwTqmdQkJd8qRr9RjSnUX9XJ24RmJRSrU1rsragP97Y',
      name: 'SAIL',
      symbol: 'SAIL',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x4c4C7B87e44bf00e413535019159044c5a2C8943',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6kwTqmdQkJd8qRr9RjSnUX9XJ24RmJRSrU1rsragP97Y/logo.png',
    },
    {
      solanaContract: 'CKaKtYvz6dKPyMvYq9Rh3UBrnNqYZAyd7iF4hJtjUvks',
      name: 'Gari',
      symbol: 'GARI',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0x7e23f3EE68024f6aE14d201eb90B3ae016521BCb',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/CKaKtYvz6dKPyMvYq9Rh3UBrnNqYZAyd7iF4hJtjUvks/logo.png',
    },
    {
      solanaContract: 'CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5',
      name: 'renBTC',
      symbol: 'renBTC',
      wChainId: 4,
      chainId: 56,
      chainName: 'Binance Smart Chain',
      isSolanaNative: true,
      ethContract: '0xEe0D4c4BC39b0765b8dA5AC9e6A5f840F88e80f4',
      decimals: 8,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5/logo.png',
    },
    {
      solanaContract: '9gP2kCy3wA1ctvYWQk75guqXuHfrEomqydHLtcTCqiLa',
      name: 'Wrapped BNB',
      symbol: 'WBNB',
      wChainId: 4,
      chainId: 56,
      decimals: 18,
      chainName: 'Binance Smart Chain',
      isSolanaNative: false,
      ethContract: '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
      logoURI: 'https://assets.coingecko.com/coins/images/12591/small/binance-coin-logo.png?1600947313',
    },
  ],
  '137': [
    {
      solanaContract: 'So11111111111111111111111111111111111111112',
      name: 'Wrapped SOL',
      symbol: 'SOL',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xd93f7E271cB87c23AaA73edC008A79646d1F9912',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png',
    },
    {
      solanaContract: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      name: 'USD Coin',
      symbol: 'USDC',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x576Cf361711cd940CD9C397BB98C4C896cBd38De',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png',
    },
    {
      solanaContract: 'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
      name: 'Serum',
      symbol: 'SRM',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x0BDc7767Be68cfBECFC9a90cDc7D0c1C8d215D08',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/logo.png',
    },
    {
      solanaContract: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      name: 'USDT',
      symbol: 'USDT',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x3553f861dEc0257baDA9F8Ed268bf0D74e45E89C',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB/logo.svg',
    },
    {
      solanaContract: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
      name: 'Wrapped Bitcoin (Sollet)',
      symbol: 'BTC',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x4653dDd751CD1dA6dFc6dd4cBf1F575d17be2e33',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E/logo.png',
    },
    {
      solanaContract: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
      name: 'Marinade staked SOL (mSOL)',
      symbol: 'mSOL',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xc60AF012b3106a2A0Ab9d3bf7dFF0E0e19886B48',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So/logo.png',
    },
    {
      solanaContract: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
      name: 'Raydium',
      symbol: 'RAY',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x5D0D8D062eb1F0971385BAE419BC5cf745cD10b0',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/logo.png',
    },
    {
      solanaContract: 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
      name: 'Star Atlas',
      symbol: 'ATLAS',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xCEf3fAe648270E1d064922283dC26f2e25D8d77f',
      decimals: 8,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx/logo.png',
    },
    {
      solanaContract: 'UXPhBoR3qG4UCiGNJfV7MqhHyFqKN68g45GoYvAeL2M',
      name: 'UXP Governance Token',
      symbol: 'UXP',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xC1c6F4B28A314221134cb684C7d9c7237225bF3C',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/UXPhBoR3qG4UCiGNJfV7MqhHyFqKN68g45GoYvAeL2M/uxp-icon-black.png',
    },
    {
      solanaContract: 'AR1Mtgh7zAtxuxGd2XPovXPVjcSdY3i4rQYisNadjfKy',
      name: 'Wrapped SUSHI (Sollet)',
      symbol: 'soSUSHI',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x0ffA1d38199B323b4F1eBD6D805d196Dcc91131d',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AR1Mtgh7zAtxuxGd2XPovXPVjcSdY3i4rQYisNadjfKy/logo.png',
    },
    {
      solanaContract: 'SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag',
      name: 'Sunny Governance Token',
      symbol: 'SUNNY',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x953B6Ea09b77F0B45498B6a5Ead26157628942c0',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag/logo.svg',
    },
    {
      solanaContract: 'GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz',
      name: 'Genopets',
      symbol: 'GENE',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xb6846dbcB48CD57d2FA07AC0A12690FFd7ED530E',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz/logo.png',
    },
    {
      solanaContract: 'MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac',
      name: 'Mango',
      symbol: 'MNGO',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x214c9481D1c8b6461859E308f04aC83F4C07657a',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac/token.png',
    },
    {
      solanaContract: 'dK83wTVypEpa1pqiBbHY3MNuUnT3ADUZM4wk9VZXZEc',
      name: 'Wrapped Aave (Sollet)',
      symbol: 'soAAVE',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xf34Bf134f1027fc4ED35F24C1CC471B70790AA41',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/dK83wTVypEpa1pqiBbHY3MNuUnT3ADUZM4wk9VZXZEc/logo.png',
    },
    {
      solanaContract: 'AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
      name: 'Aurory',
      symbol: 'AURY',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x6E8aaF74cB7454C9103848861E47f67A8aa5Db65',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP/logo.png',
    },
    {
      solanaContract: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
      name: 'Saber Protocol Token',
      symbol: 'SBR',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x7686E89BC3d657AB23eECC712c8c79548971eb23',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1/logo.svg',
    },
    {
      solanaContract: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
      name: 'Bonfida',
      symbol: 'FIDA',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xb83218520B9515C645c09953235C20936beEfB42',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp/logo.svg',
    },
    {
      solanaContract: '3jzdrXXKxwkBk82u2eCWASZLCKoZs1LQTg87HBEAmBJw',
      name: 'FLOOF',
      symbol: 'FLOOF',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x79311dE967845458Aa3bA8d6Df442fD34746144d',
      decimals: 9,
      logoURI: 'https://raw.githubusercontent.com/GreenFailure/Floof/main/OkyT9kpz_400x400.png',
    },
    {
      solanaContract: 'RLBxxFkseAZ4RgJH3Sqn8jXxhmGoz9jWxDNJMh8pL7a',
      name: 'Rollbit Coin',
      symbol: 'RLB',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x2a28bf1789Ec27B312030B8aE16E50192a9A75ef',
      decimals: 2,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/RLBxxFkseAZ4RgJH3Sqn8jXxhmGoz9jWxDNJMh8pL7a/logo.png',
    },
    {
      solanaContract: '4dmKkXNHdgYsXqBHCuMikNQWwVomZURhYvkkX5c4pQ7y',
      name: 'Synthetify',
      symbol: 'SNY',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x02836036380e9613BC9a1992Fff9e17bd9f5a982',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4dmKkXNHdgYsXqBHCuMikNQWwVomZURhYvkkX5c4pQ7y/logo.png',
    },
    {
      solanaContract: '3FoUAsGDbvTD6YZ4wVKJgTB76onJUKz7GPEBNiR5b8wc',
      name: 'Cheems',
      symbol: 'CHEEMS',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x5561683aB5aAd562c338dA0DF64A7B768772b37f',
      decimals: 4,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/3FoUAsGDbvTD6YZ4wVKJgTB76onJUKz7GPEBNiR5b8wc/logo.png',
    },
    {
      solanaContract: 'PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44',
      name: 'PRT (Parrot Protocol)',
      symbol: 'PRT',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x096831535ddEdBbD6F67157d203895F1e76cf4DC',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44/logo.svg',
    },
    {
      solanaContract: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
      name: 'Orca',
      symbol: 'ORCA',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x276CFEe75f638B4405D1cF5f871092eFA70a0C6A',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE/logo.png',
    },
    {
      solanaContract: 'kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6',
      name: 'KIN',
      symbol: 'KIN',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0xae20bC21D17fAfB945551D4Fd15bf4f136e106F7',
      decimals: 5,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/logo.png',
    },
    {
      solanaContract: 'CwChm6p9Q3yFrjzVeiLTTbsoJkooscof5SJYZc2CrNqG',
      name: 'ETHBULL',
      symbol: 'ETHBULL',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x48b7c7f322b8Ceec48c0C2CcE225AdF97710e0f7',
      decimals: 6,
      logoURI: '',
    },
    {
      solanaContract: '4BzxVoBQzwKoqm1dQc78r42Yby3EzAeZmMiYFdCjeu5Z',
      name: 'Swole Doge',
      symbol: 'SWOLE',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x1B0f10F7baDa9aC10B7343fAF3bB1A7732761620',
      decimals: 9,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4BzxVoBQzwKoqm1dQc78r42Yby3EzAeZmMiYFdCjeu5Z/logo.png',
    },
    {
      solanaContract: 'MEANeD3XDdUmNMsRGjASkSWdC8prLYsoRJ61pPeHctD',
      name: 'MEAN',
      symbol: 'MEAN',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x4867B60aD7C6aDc98653f661f1AEA31740986bA5',
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/MEANeD3XDdUmNMsRGjASkSWdC8prLYsoRJ61pPeHctD/logo.svg',
    },
    {
      solanaContract: 'CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5',
      name: 'renBTC',
      symbol: 'renBTC',
      wChainId: 5,
      chainId: 137,
      chainName: 'Polygon',
      isSolanaNative: true,
      ethContract: '0x3063C361D32B2d18FE00eb88378d10bf9Ff50F03',
      decimals: 8,
      logoURI:
        'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5/logo.png',
    },
    {
      solanaContract: 'Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG',
      name: 'Wrapped Matic',
      symbol: 'WMATIC',
      wChainId: 5,
      chainId: 137,
      decimals: 18,
      chainName: 'Polygon',
      isSolanaNative: false,
      ethContract: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
      logoURI: 'https://assets.coingecko.com/coins/images/14073/small/matic.png?1628852392',
    },
  ],
  '365': [
    {
      name: 'Tetha Fuel',
      symbol: 'TFUEL',
      chainId: 365,
      decimals: 18,
      chainName: 'Tetha',
      logoURI: 'https://assets.coingecko.com/coins/images/8029/small/1_0YusgngOrriVg4ZYx4wOFQ.png?1553483622',
    },
  ],
}

export default legitTokens
